version: "3"
services:
  db:
    container_name: "mysql"
    image: mysql:5.6
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD="mysecretpassword"
    networks:
      - backend

  users:
    container_name: "users"
    image: user-service:v1
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=mysecretpassword
    ports:
      - 5000:8000
    networks:
      - backend
    links:
      - db
    depends_on:
      - db

networks:
  backend:

volumes:
  db-data:
