apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    app: users
spec:
  selector:
    app: users
    tier: api
  ports:
  - protocol: TCP
    name: "http"
    port: 8000
    targetPort: 8000
  type: LoadBalancer
